### ISSUE TITLE
add span tag for each "li"(preview render)

### ISSUE THREAD

**Issue by jakekwak** [Vanessa219/vditor#518]
I am making another theme using https://theme.typora.io/theme/cobalt/
but I can not apply the below CSS.

```
      ol>li,
      ul>li {
        color: #f0b752;
      }

      ol>li>*,
      ul>li>* {
        color: #b0b0b0;
      }
```

but when added the span tag for `li`,  it works.

![6](https://user-images.githubusercontent.com/15811943/86044070-32eead80-ba0f-11ea-8b58-ccf518b7a7b2.PNG)
1. with span tag
2. no span tag

@88250 if possible,  please add span tag.

**Comment by Vanessa219** [comment]
https://hacpai.com/article/1566565149141?r=Vanessa maybe can help you
```css
ol {
  list-style: none;
  li::before {
    counter-increment: counter;
    content: counters(counter, '.') ' ';
    color: red;
  }
}

ul {
  list-style: none;
  li::before {
    padding-right: 5px;
    content: '•';
    color: blue;
  }
}
```
