### ISSUE TITLE
支持表格横向滚动

### ISSUE THREAD

**Issue by Vanessa219** [Vanessa219/vditor#957]

**Comment by clover52** [comment]
![image](https://user-images.githubusercontent.com/33340057/112605382-3609b380-8e52-11eb-837a-db12869154e9.png)
此处添加滚动条，为表格表格过长时，方便查看隐藏信息

整体内容的滚动条，建议删除，因为无论是哪里的内容需要横向滚动条，靠最外面的滚动条都会有类似的情况发生，最好都是单独设置横向滚动条

**Comment by lzh370** [comment]
```css
.vditor-reset table { display: block;word-break: keep-all;width: 100%; }
.vditor-reset td,th { white-space:nowrap;}
```
